export const FETCH_AUTH_ID = "FETCH_AUTH_ID";

export const FETCH_REST_DATA = "FETCH_REST_DATA";
export const REMOVE_REST_DATA = "REMOVE_REST_DATA";

export const FETCH_REVIEW_DATA = "FETCH_REVIEW_DATA";
export const REMOVE_REVIEW_DATA = "REMOVE_REVIEW_DATA";

export const FETCH_MENU_DATA = "FETCH_MENU_DATA";
export const REMOVE_MENU_DATA = "REMOVE_MENU_DATA";

export const FETCH_CATEGORY_DATA = "FETCH_CATEGORY_DATA";
export const REMOVE_CATEGORY_DATA = "REMOVE_CATEGORY_DATA";

export const FETCH_PHOTOS_DATA = "FETCH_PHOTOS_DATA";
export const REMOVE_PHOTOS_DATA = "REMOVE_PHOTOS_DATA";

export const FETCH_BOOKINGS_DATA = "FETCH_BOOKINGS_DATA";
export const REMOVE_BOOKINGS_DATA = "REMOVE_BOOKINGS_DATA";