export const FETCH_USER_DATA = "FETCH_USERS_DATA";
export const FETCH_RESTOES_DATA = "FETCH_RESTOES_DATA";
export const FETCH_BOOKINGS_DATA = "FETCH_BOOKINGS_DATA";
export const FETCH_CATEGORY_DATA = "FETCH_CATEGORY_DATA";
export const FETCH_PACKAGES_DATA = "FETCH_PACKAGES_DATA";
export const FETCH_AUTH_ID = "FETCH_AUTH_ID";